export const ADD_TRS = 'ADD_TRS';
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';
export const DATA_IS_LOADING = 'DATA_IS_LOADING';
export const FETCH_TRS_SUCCESS = 'FETCH_TRS_SUCCESS';
export const FETCH_CAT_SUCCESS = 'FETCH_CAT_SUCCESS';
export const FETCH_BAL_SUCCESS = 'FETCH_BAL_SUCCESS';
export const ACTIVE_MONTH_CHANGED = 'ACTIVE_MONTH_CHANGED';
