const ADD_TRS = 'ADD_TRS';
const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';
const DATA_IS_LOADING = 'DATA_IS_LOADING';
const FETCH_TRS_SUCCESS = 'FETCH_TRS_SUCCESS';
const FETCH_CAT_SUCCESS = 'FETCH_CAT_SUCCESS';
const FETCH_BAL_SUCCESS = 'FETCH_BAL_SUCCESS';
const ACTIVE_MONTH_CHANGED = 'ACTIVE_MONTH_CHANGED';

export { ADD_TRS, DATA_FETCH_ERROR, DATA_IS_LOADING, FETCH_TRS_SUCCESS, FETCH_CAT_SUCCESS, FETCH_BAL_SUCCESS, ACTIVE_MONTH_CHANGED };
